# Default values for gvm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# To change all the gvm tags together you can use go templates.
# Example:
#
# global:
#   gvmImageTag: "10"
# image:
#   gvmd:
#     tag: "{{ .Values.global.gvmImageTag }}"
#   gsad:
#     tag: "{{ .Values.global.gvmImageTag }}"
#   openvas:
#     tag: "{{ .Values.global.gvmImageTag }}"
  
image:
  gvmd:
    registry: "docker.io"
    repository: "admirito/gvmd"
    tag: "11"
    pullPolicy: IfNotPresent
  gsad:
    registry: "docker.io"
    repository: "admirito/gsad"
    tag: "11"
    pullPolicy: IfNotPresent
  openvas:
    registry: "docker.io"
    repository: "admirito/openvas"
    tag: "11"
    pullPolicy: IfNotPresent
  socat:
    registry: "docker.io"
    repository: "alpine/socat"
    tag: "1.0.3"
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

labels:
  applicationName: gvm
  partOf: gvm
  instanceSuffix: ""

gvmdService:
  type: ClusterIP
  port: 9390

openvasService:
  type: ClusterIP
  port: 9391

#gsa service
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  gvmd: {}
  gvmdOpenvasConnector: {}
  openvas: {}
  openvasListener: {}
  openvasRedisConnector: {}
  gsad: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# call nvt-sync after chart installation
syncNvtPluginsAfterInstall: true

# call scapdata-sync and certdata-sync after chart installation
syncScapCertDataAfterInstall: false

# the value of dataSubPathPrefix will be used as the prefix for
# subPath in volumeMounts of gvmd/openvas deployments for the
# persistent volume specified by persistence parameters
dataSubPathPrefix: ""

# This is data persistence for nasl plugins / scap data / cert
# data. For database persistence see gvmd-db and openvas-redis.
persistence:
  # It is highly recommended not to disable the
  # persistence. Without enabling a persistent volume
  # sharing nvt-plugins between gvmd and openvas-scanner is not
  # possible
  enabled: true

  # existing PVC to be used instead of creating a new one
  existingClaim: ""

  # PVC annotations
  # annotations:

  accessMode: ReadWriteOnce
  # storageClass:
  # volumeName:
  size: 1Mi

gvmd-db:
  image:
    # You can override this one, or global.imageRegistry
    registry: "docker.io"
    repository: admirito/gvm-postgres
    tag: "10"
  volumePermissions:
    enabled: false
  securityContext:
    enabled: false
  postgresqlUsername: gvmduser
  postgresqlDatabase: gvmd
  extraEnv: {}
  #persistence:
  #  existingClaim:

openvas-redis:
  image:
    # You can override this one, or global.imageRegistry
    registry: "docker.io"
    repository: bitnami/redis
    tag: "5.0"
  cluster:
    enabled: false
  usePassword: false
  #persistence:
  #  existingClaim:
